version: '3'

services:
  postgres-sql-db:
    image: postgres
    environment:
      - POSTGRES_USER=rocket
      - POSTGRES_PASSWORD=E89x7.Aisx
      - POSTGRES_DB=rocket
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql